#################################
########## AdiAuth ##############
############### -by ad1tya2 #####

#Dont touch At any cost
configversion: 2

#storage
#Options available, h2 and mysql
#H2 is also a local storage system, no external database is needed
#h2 is a good alternative to sqlite
database: mysql

#database settings for mysql if it is enabled
mysql:
  username: root
  password:
  database: lunik
  host: localhost

#The tme to keep a player logged in for in Minutes
#So that they don't have to login everytime they reconnect
#Note that the session will be reset when they join from a new ip
sessionTime: 120


#The servers where they will be teleported to login
authServers:
  - login

#The servers where players will be sent to after logging in
lobbyServers:
  - lobby

#The url of a backup server to use, Contact me on my discord if you wish to use it
#Note: I dont give backup server for free xD
backupServer: ''

#Use the backup server always
forceBackupServer: false

#Give darkness effect to players who haven't logged in
#If you want to reload this then you will need to reload this on bungee and restart the backend spigot server
blindness: false

#Prevent players who haven't logged in from moving
#If you want to reload this then you will need to reload this on bungee and restart the backend spigot server
freezePlayers: false

#The interval in seconds to check if a server is online or not
serverCheckInterval: 10

#Commands that can be executed without being logged in
whitelistedCommands:
  - /register
  - /reg
  - /login
  - /2fa

#The maximum number of premium accounts that can join from a single ip
maxPremiumAccounts: 3

#The maximum number of cracked accounts that can be created by a single ip
maxCrackedAccounts: 2

#The maximum number of accounts that can be created in total by a single ip
#If maxPremiumAccounts is 2
# and maxCrackedAccounts is 2
# But if maxTotalAccounts is 3
# Then only the first 3 accounts will be allowed
maxTotalAccounts: 3

#The message to show when a cracked person with a premium name tries to login for the second time
#Leave empty if you dont want this feature to be enabled
secondAttempt: '&cSessão inválida: Uma conta original já é existente com esse nick.'

#Whether to disconnect the player if he enters the wrong password
disconnectOnWrongPass: false

#The time in seconds that the players have to login or register
authTime: 120

#Discord 2fa system
discord:
  enabled: false
  bot-token: ''
  loginButtonChannel: ''
  #Role to give on successfull 2fa registration, it will be taken if the person disables 2fa
  #Keep empty if you dont want to enable this feature
  roleToGive: ''
  activityStatus: 'Securing your server with AdiAuth :)'
  buttonMessage: Click on this button to login!
  buttonText: Login
  #Compulsory for is a list of luckperms groups for which using discord 2fa is compulsory
  #This feature will not be enabled if you dont have luckperms.
  compulsory-for:
    - 'staff'
    - 'owners'
  #Important Note: Multiple accounts cannot be linked to one discord id.

messages:
  registerMessage: '&e&LAUTH &fUtilize &c/register <senha> &epara autenticar-se.'
  loginMessage: '&eWelcome! Please &c/login <password> &eto play'
  registerTitle: '&2/register <password>'
  loginTitle: '&2/login <password>'
  registerError: '&cInvalid Format! Please use /register <password>'
  alreadyRegistered: '&cYou are already registered. Please use /changepass <oldpassword> <newpassword> if you want to change your pass'
  loginAndRegisterSuccess: |-
    &aWelcome to INMC, have fun!
    &7----------------------------
     &bTip:- &2Use /2fa register
     To enable 2fa and secure
        your account
    &7----------------------------
  loginAndRegisterSuccessTitle: '&aAutenticado!'
  alreadyLoggedIn: '&cVocê não precisa se autenticar.'
  loginError: '&cUso: /login <senha>'
  loginNotRegistered: '&cVocê não possui uma conta registrada.'
  loginWrongPass: '&cA senha está incorreta.'
  noServersAvailable: '&cNão foi possivel conectar-se ao LOBBY.'
  logoutMessage: '&aAutenticado com sucesos, redirecionando ao Lobby!'
  changePassError: '&cUso: /changepass <senha antiga> <senha nova>'
  successfulChangePass: '&aVocê alterou sua senha com sucesso!'
  genericPremiumError: '&cEsse comando é inexistente.'
  tooManyAccounts: '&cErro: &8[Há muitas contas neste endereço de IP]'
  #TIMELEFT will be replaced by number of seconds left
  loginRegisterBossBar: '&eVocê tem &cTIMELEFT segundos&e restantes par autenticar-se.'
  authTimeExceeded: '&cVocê demorou muito para autenticar-se!'
  #BOTNAME is automatically replaced to the name of the discord bot with its hashtag
  #THISLINK and CODE is also automatically replaced
  #You have to replace discordInviteLinkHere
  discordRegisterMessage: |-
    &bPlease dm &dCODE &bto the Discord Bot
    The Bot's name is &2BOTNAME &byou can either dm it directly
    Or click on THISLINK to open the dms with the bot!
    You can find it in our server &ddiscordInviteLinkHere
  #CHANNELNAME is replaced by the name of the channel
  #THISLINK is replaced by an url to open the channel in the browser
  discordLoginMessage: |-
    &bPlease click on the button in CHANNELNAME to login
    &eYou can also click on THISLINK to open the channel directly